Repository the-events-calendar/gigpress, pull requests merged in 2020-04, with the labels that each got.

#45 [GP-5] Update new.php
  admin/new.php
Labels: code review, needs changelog

#48 tweaks and changelog
  admin/new.php
  readme.txt
Labels: merge

#49 [GP-3] Fixed array offset deprecated errors in PHP 7.4
  gigpress.php
  readme.txt
Labels: code review

#50 Release/g20.04
  admin/db.php
  admin/handlers.php
  admin/new.php
  admin/settings.php
  gigpress.php
  readme.txt
  templates/related.php
  templates/shows-list.php
Labels: hold
